import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CONTEXT_PULL_SCRIPT, CONTEXT_VALIDATE_SCRIPT, OFFICIAL_CONTEXT_REPOSITORY } from "./constants.js";
import { parseJsonc, stripJsonc } from "./files.js";
import { scaffoldProject } from "./scaffold.js";

describe("scaffoldProject", () => {
  it("creates the complete monorepo branch", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "monorepo-template-"));
    const calls: string[] = [];
    const root = await scaffoldProject(
      {
        projectName: "example",
        architecture: "monorepo",
        frontend: "vite",
        backend: "hono",
      },
      {
        cwd,
        run: async (command, args) => { calls.push([command, ...args].join(" ")); },
      },
    );

    const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
    expect(packageJson.scripts["context:pull"]).toBe(CONTEXT_PULL_SCRIPT);
    expect(packageJson.scripts["context:validate"]).toBe(CONTEXT_VALIDATE_SCRIPT);
    expect(await readFile(join(root, "pnpm-workspace.yaml"), "utf8")).toContain('"app/*"');
    expect(await readFile(join(root, "app/web/src/main.tsx"), "utf8")).toContain("createRoot");
    expect(await readFile(join(root, "app/api/src/index.ts"), "utf8")).toContain("Hono");
    expect(await readFile(join(root, "app/api/src/index.ts"), "utf8")).toContain(
      'app.route("/samples", createSampleRoutes(sampleStore))',
    );
    expect(await readFile(join(root, "app/api/src/index.ts"), "utf8")).toContain("bodyLimit({ maxSize: 100 * 1024");
    expect(JSON.parse(await readFile(join(root, "app/api/tsconfig.json"), "utf8")).compilerOptions.types).toEqual(["node"]);
    expect(JSON.parse(await readFile(join(root, "app/api/package.json"), "utf8")).dependencies.zod).toBe("latest");
    for (const layer of ["services", "controllers", "data"]) {
      for (const action of ["create", "update", "delete"]) {
        const suffix = layer === "services" ? "service" : layer === "controllers" ? "controller" : "data";
        expect(await readFile(
          join(root, `app/api/src/modules/sample/${layer}/${action}-sample.${suffix}.ts`),
          "utf8",
        )).toContain(`${action}Sample`);
      }
    }
    expect(await readFile(join(root, "app/api/src/modules/sample/dto/sample.dto.ts"), "utf8")).toContain(".strict()");
    expect(await readFile(join(root, "app/api/src/modules/sample/sample.routes.ts"), "utf8")).toContain('patch("/:id"');
    expect(await readFile(join(root, "packages/db/prisma/schema.prisma"), "utf8")).toContain('provider = "prisma-kysely"');
    expect(await readFile(join(root, "packages/db/prisma.config.ts"), "utf8")).toContain("defineConfig");
    const databasePackage = JSON.parse(await readFile(join(root, "packages/db/package.json"), "utf8"));
    expect(databasePackage.devDependencies["@types/node"]).toBe("latest");
    expect(JSON.parse(await readFile(join(root, "packages/db/tsconfig.json"), "utf8")).compilerOptions.types).toEqual(["node"]);
    expect(await readFile(join(root, "packages/tsconfig/package.json"), "utf8")).toContain("@workspace/tsconfig");
    expect(await readFile(join(root, "packages/eslint-config/package.json"), "utf8")).toContain("@workspace/eslint-config");
    for (const directory of ["schemas", "types", "utils", "constants"]) {
      expect(await readFile(join(root, `packages/shared/src/${directory}/index.ts`), "utf8")).toBe("export {};\n");
    }
    expect(await readFile(join(root, "packages/shared/src/index.ts"), "utf8")).toContain(
      'export * from "./schemas/index.js";',
    );
    expect(await readFile(join(root, ".npmrc"), "utf8")).toContain("prefer-workspace-packages=true");
    expect(await readFile(join(root, ".nvmrc"), "utf8")).toBe("20\n");
    expect(await readFile(join(root, ".github/workflows/ci.yml"), "utf8")).toContain("pnpm build");
    // deploy.yml and dependabot.yml are no longer generated by default
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("context-factory/orchestrator/SHARED.md");
    expect(await readFile(join(root, "docs/design-pattern.md"), "utf8")).toContain("Framework default");
    expect(calls[0]).toContain("bridge --target .");
    expect(existsSync(join(root, "context-factory/context-manifest.json"))).toBe(true);
  });

  it("routes shadcn/ui into packages/ui and configures Astro as its consumer", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "shadcn-monorepo-"));
    const root = await scaffoldProject(
      {
        projectName: "shadcn-app",
        architecture: "monorepo",
        frontend: "astro",
        backend: "hono",
        styling: "shadcn",
      },
      { cwd, run: async () => undefined },
    );

    const uiPackage = JSON.parse(await readFile(join(root, "packages/ui/package.json"), "utf8"));
    const webPackage = JSON.parse(await readFile(join(root, "app/web/package.json"), "utf8"));
    expect(uiPackage.dependencies.shadcn).toBe("latest");
    expect(uiPackage.dependencies["tailwind-merge"]).toBe("latest");
    expect(uiPackage.exports["./components/*"]).toBe("./src/components/*.tsx");
    expect(webPackage.dependencies["@workspace/ui"]).toBe("workspace:*");
    expect(webPackage.dependencies["@astrojs/react"]).toBe("latest");
    expect(await readFile(join(root, "packages/ui/components.json"), "utf8")).toContain("@workspace/ui/components");
    expect(await readFile(join(root, "app/web/components.json"), "utf8")).toContain("../../packages/ui/src/styles/globals.css");
    expect(await readFile(join(root, "app/web/astro.config.mjs"), "utf8")).toContain("integrations: [react()]");
    expect(await readFile(join(root, "app/web/src/pages/index.astro"), "utf8")).toContain('@workspace/ui/globals.css');
    expect(await readFile(join(root, "docs/design-pattern.md"), "utf8")).toContain(
      "routes shared primitives into `packages/ui`",
    );
  });

  it("configures daisyUI in packages/ui with the Next.js PostCSS adapter", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "daisy-monorepo-"));
    const root = await scaffoldProject(
      {
        projectName: "daisy-app",
        architecture: "monorepo",
        frontend: "next",
        backend: "express",
        styling: "daisyui",
      },
      { cwd, run: async () => undefined },
    );

    const uiPackage = JSON.parse(await readFile(join(root, "packages/ui/package.json"), "utf8"));
    const webPackage = JSON.parse(await readFile(join(root, "app/web/package.json"), "utf8"));
    expect(uiPackage.devDependencies.daisyui).toBe("latest");
    expect(webPackage.devDependencies["@tailwindcss/postcss"]).toBe("latest");
    expect(await readFile(join(root, "packages/ui/src/styles.css"), "utf8")).toContain('@plugin "daisyui"');
    expect(await readFile(join(root, "app/web/postcss.config.mjs"), "utf8")).toContain("@tailwindcss/postcss");
    expect(await readFile(join(root, "app/web/app/layout.tsx"), "utf8")).toContain('@workspace/ui/styles.css');
  });

  it("configures Bootstrap in packages/ui without adding Tailwind tooling", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "bootstrap-monorepo-"));
    const root = await scaffoldProject(
      {
        projectName: "bootstrap-app",
        architecture: "monorepo",
        frontend: "vite",
        backend: "hono",
        styling: "bootstrap",
      },
      { cwd, run: async () => undefined },
    );

    const uiPackage = JSON.parse(await readFile(join(root, "packages/ui/package.json"), "utf8"));
    const webPackage = JSON.parse(await readFile(join(root, "app/web/package.json"), "utf8"));
    expect(uiPackage.dependencies.bootstrap).toBe("latest");
    expect(uiPackage.devDependencies.tailwindcss).toBeUndefined();
    expect(webPackage.devDependencies["@tailwindcss/vite"]).toBeUndefined();
    expect(await readFile(join(root, "packages/ui/src/styles.css"), "utf8")).toContain(
      '@import "bootstrap/dist/css/bootstrap.min.css"',
    );
    expect(await readFile(join(root, "app/web/src/style.css"), "utf8")).toContain('@workspace/ui/styles.css');
  });

  it("configures standalone Tailwind CSS in packages/ui and the Vite build adapter", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tailwind-monorepo-"));
    const root = await scaffoldProject(
      {
        projectName: "tailwind-app",
        architecture: "monorepo",
        frontend: "vite",
        backend: "hono",
        styling: "tailwind",
      },
      { cwd, run: async () => undefined },
    );

    const uiPackage = JSON.parse(await readFile(join(root, "packages/ui/package.json"), "utf8"));
    const webPackage = JSON.parse(await readFile(join(root, "app/web/package.json"), "utf8"));
    expect(uiPackage.devDependencies.tailwindcss).toBe("latest");
    expect(uiPackage.devDependencies.daisyui).toBeUndefined();
    expect(uiPackage.dependencies?.shadcn).toBeUndefined();
    expect(webPackage.devDependencies["@tailwindcss/vite"]).toBe("latest");
    expect(await readFile(join(root, "packages/ui/src/styles.css"), "utf8")).toContain('@import "tailwindcss"');
    expect(await readFile(join(root, "app/web/vite.config.ts"), "utf8")).toContain("tailwindcss()");
  });

  it("configures shadcn/ui inside a standard Vite application (built-in generator)", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "shadcn-standard-"));
    // No mock runner needed: built-in generator is used for vite (no external dlx calls)
    const root = await scaffoldProject(
      {
        projectName: "standard-web",
        architecture: "frontend",
        frontend: "vite",
        styling: "shadcn",
      },
      { cwd, run: async () => undefined },
    );

    // Root has proxy scripts; shadcn deps go into app/package.json
    const appPackageJson = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
    expect(appPackageJson.dependencies?.shadcn ?? appPackageJson.devDependencies?.shadcn).toBeDefined();
    expect(await readFile(join(root, "app/src/lib/utils.ts"), "utf8")).toContain("twMerge(clsx(inputs))");
    // No packages/ui in a single-app frontend layout
    await expect(readFile(join(root, "packages/ui/package.json"), "utf8")).rejects.toThrow();
    // context-factory is at root, not in app/
    expect(existsSync(join(root, "app/context-factory"))).toBe(false);
    // README mentions app/ layout
    expect(await readFile(join(root, "README.md"), "utf8")).toContain("app/");
  });

  it("creates a standard backend without workspace files", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "standard-template-"));
    const root = await scaffoldProject(
      { projectName: "api", architecture: "backend", backend: "express" },
      { cwd, run: async () => undefined },
    );
    // Root package.json has proxy scripts and context orchestration
    const rootPackageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
    expect(rootPackageJson.scripts["context:pull"]).toBe(CONTEXT_PULL_SCRIPT);
    expect(rootPackageJson.scripts["context:validate"]).toBe(CONTEXT_VALIDATE_SCRIPT);
    expect(rootPackageJson.scripts.dev).toBe("pnpm --prefix app dev");
    // App-level package.json has framework dependencies
    const appPackageJson = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
    expect(appPackageJson.dependencies.express).toBe("latest");
    expect(appPackageJson.dependencies.zod).toBe("latest");
    expect(JSON.parse(await readFile(join(root, "app/tsconfig.json"), "utf8")).compilerOptions.types).toEqual(["node"]);
    expect(await readFile(join(root, ".npmrc"), "utf8")).toContain("engine-strict=true");
    expect(await readFile(join(root, ".nvmrc"), "utf8")).toBe("20\n");
    expect(await readFile(join(root, ".github/workflows/ci.yml"), "utf8")).toContain("pnpm build");
    expect(await readFile(join(root, "app/src/index.ts"), "utf8")).toContain(
      'app.use("/samples", createSampleRoutes(sampleStore))',
    );
    expect(await readFile(join(root, "app/src/index.ts"), "utf8")).toContain('express.json({ limit: "100kb" })');
    expect(await readFile(join(root, "app/src/modules/sample/controllers/create-sample.controller.ts"), "utf8")).toContain(
      "createSampleDtoSchema.safeParse",
    );
    await expect(readFile(join(root, "pnpm-workspace.yaml"), "utf8")).rejects.toThrow();
    await expect(readFile(join(root, "turbo.json"), "utf8")).rejects.toThrow();
    // context-factory IS at root (outside app/) — this is the key design invariant
    // It may not exist in test env (bundled CF path doesn't exist), but we verify it's NOT inside app/
    expect(existsSync(join(root, "app/context-factory"))).toBe(false);
  });

  it("rejects path traversal and existing targets", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "guard-template-"));
    const options = { cwd, run: async () => undefined };
    await expect(scaffoldProject(
      { projectName: "../escape", architecture: "backend", backend: "express" },
      options,
    )).rejects.toThrow("Invalid project name");
    await scaffoldProject(
      { projectName: "same", architecture: "backend", backend: "express" },
      options,
    );
    await expect(scaffoldProject(
      { projectName: "same", architecture: "backend", backend: "express" },
      options,
    )).rejects.toThrow("Target already exists");
  });

  it("requires a repository URL for Git-backed context sync if empty", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "git-context-template-"));
    await expect(scaffoldProject(
      { projectName: "submodule-project", architecture: "backend", backend: "express" },
      { cwd, contextRepository: "", run: async () => undefined },
    )).rejects.toThrow("A context-factory repository URL is required for Git submodule sync.");
  });

  it("allows overriding the context-factory repository URL", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "git-custom-repo-"));
    const calls: string[] = [];
    await scaffoldProject(
      { projectName: "custom-repo-project", architecture: "backend", backend: "express" },
      {
        cwd,
        contextRepository: "https://example.com/custom/context-factory.git",
        run: async (command, args) => { calls.push([command, ...args].join(" ")); },
      },
    );
    expect(calls).toEqual([
      "git init",
      "git submodule add https://example.com/custom/context-factory.git context-factory",
    ]);
  });

  it("initializes packages/ui with React support by default in monorepo regardless of styling", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "ui-react-default-"));
    const root = await scaffoldProject(
      {
        projectName: "mono-react-ui",
        architecture: "monorepo",
        frontend: "vite",
        backend: "hono",
        styling: "none",
      },
      { cwd, run: async () => undefined },
    );

    const uiPackage = JSON.parse(await readFile(join(root, "packages/ui/package.json"), "utf8"));
    const uiTsconfig = JSON.parse(await readFile(join(root, "packages/ui/tsconfig.json"), "utf8"));
    expect(uiPackage.peerDependencies.react).toBe("latest");
    expect(uiPackage.peerDependencies["react-dom"]).toBe("latest");
    expect(uiPackage.devDependencies["@types/react"]).toBe("latest");
    expect(uiPackage.devDependencies["@types/react-dom"]).toBe("latest");
    expect(uiTsconfig.extends).toBe("@workspace/tsconfig/react.json");
    expect(uiTsconfig.compilerOptions.jsx).toBe("react-jsx");
    expect(uiTsconfig.include).toContain("src/**/*.tsx");
  });

  it("uses built-in generators for vite, next, and astro — no external dlx calls", async () => {
    for (const [name, frontend, check] of [
      ["next-built-in", "next", "next"],
      ["astro-built-in", "astro", "astro"],
      ["vite-built-in", "vite", "vite"],
    ] as const) {
      const cwd = await mkdtemp(join(tmpdir(), `${name}-`));
      const pnpmCalls: string[] = [];
      const root = await scaffoldProject(
        { projectName: name, architecture: "frontend", frontend },
        {
          cwd,
          run: async (command, args) => {
            if (command === "pnpm") pnpmCalls.push(args.join(" "));
          },
        },
      );
      // No pnpm dlx create-* calls should have been made
      const dlxCalls = pnpmCalls.filter((a) => a.includes("dlx") && a.includes("create-"));
      expect(dlxCalls).toHaveLength(0);
      // Built-in generator created app/package.json
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.dependencies?.[check] ?? appPkg.devDependencies?.[check]).toBeDefined();
    }
  });

  it("built-in vite generator creates valid tsconfig.json without external network calls", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "vite-builtin-"));
    const root = await scaffoldProject(
      { projectName: "vite-app", architecture: "frontend", frontend: "vite" },
      { cwd, run: async () => undefined },
    );
    // app/ contains the vite project
    const tsconfig = JSON.parse(await readFile(join(root, "app/tsconfig.json"), "utf8"));
    expect(tsconfig.compilerOptions.module).toBe("ESNext");
    expect(tsconfig.compilerOptions.jsx).toBe("react-jsx");
    const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
    expect(appPkg.scripts.dev).toBe("vite");
    expect(appPkg.devDependencies.vite).toBeDefined();
  });

  describe("matrix: project architecture & styling combinations (Unit 04.01)", () => {
    it("scaffolds Frontend Web App (Next.js + shadcn/ui)", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-next-shadcn-"));
      const root = await scaffoldProject(
        { projectName: "web-next", architecture: "frontend", frontend: "next", styling: "shadcn" },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/components.json"))).toBe(true);
      expect(existsSync(join(root, "app/src/app"))).toBe(true);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.dependencies?.next ?? appPkg.devDependencies?.next).toBeDefined();
    });

    it("scaffolds Frontend Web App (Astro + Tailwind)", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-astro-tw-"));
      const root = await scaffoldProject(
        { projectName: "web-astro", architecture: "frontend", frontend: "astro", styling: "tailwind" },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/astro.config.mjs"))).toBe(true);
      expect(existsSync(join(root, "app/src/pages"))).toBe(true);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.dependencies?.astro ?? appPkg.devDependencies?.astro).toBeDefined();
    });

    it("scaffolds Frontend Web App (React + Vite + daisyUI)", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-vite-daisy-"));
      const root = await scaffoldProject(
        { projectName: "web-vite", architecture: "frontend", frontend: "vite", styling: "daisyui" },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/vite.config.ts"))).toBe(true);
      expect(existsSync(join(root, "app/src/main.tsx"))).toBe(true);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.devDependencies?.daisyui ?? appPkg.dependencies?.daisyui).toBeDefined();
    });

    it("scaffolds Backend API (Hono) without frontend styling files", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-backend-hono-"));
      const root = await scaffoldProject(
        { projectName: "api-hono", architecture: "backend", backend: "hono" },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/src/modules/sample"))).toBe(true);
      expect(existsSync(join(root, "app/components.json"))).toBe(false);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.dependencies.hono).toBe("latest");
      expect(appPkg.dependencies.tailwindcss).toBeUndefined();
    });

    it("scaffolds Backend API (Express) without frontend styling files", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-backend-express-"));
      const root = await scaffoldProject(
        { projectName: "api-express", architecture: "backend", backend: "express" },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/src/modules/sample"))).toBe(true);
      expect(existsSync(join(root, "app/components.json"))).toBe(false);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);
      const appPkg = JSON.parse(await readFile(join(root, "app/package.json"), "utf8"));
      expect(appPkg.dependencies.express).toBe("latest");
    });

    it("scaffolds Fullstack Monorepo (Next.js + Hono + shadcn/ui)", async () => {
      const cwd = await mkdtemp(join(tmpdir(), "matrix-monorepo-"));
      const root = await scaffoldProject(
        {
          projectName: "fullstack-app",
          architecture: "monorepo",
          frontend: "next",
          backend: "hono",
          styling: "shadcn",
        },
        { cwd, run: async () => undefined },
      );
      expect(existsSync(join(root, "app/web"))).toBe(true);
      expect(existsSync(join(root, "app/api"))).toBe(true);
      expect(existsSync(join(root, "packages/db"))).toBe(true);
      expect(existsSync(join(root, "packages/ui"))).toBe(true);
      expect(existsSync(join(root, "context-factory"))).toBe(true);
      expect(existsSync(join(root, "app/context-factory"))).toBe(false);

      const workspaceYaml = await readFile(join(root, "pnpm-workspace.yaml"), "utf8");
      expect(workspaceYaml).toContain("app/*");
      expect(workspaceYaml).toContain("packages/*");
    });
  });

});

describe("JSONC parser", () => {
  it("strips single-line and multi-line comments and trailing commas", () => {
    const raw = `
    // Leading comment
    {
      "name": "test", /* inline comment */
      "nested": {
        "url": "https://example.com/api?q=1//not-a-comment", // line comment
        "blockInStr": "/* also not comment */",
        "trailingCommaInStr": "a, } b, ]",
        "items": [
          1,
          2,
          /* comment before trailing comma */
          3, // trailing comma after this
        ],
      },
    }
    `;
    const parsed = parseJsonc<{
      name: string;
      nested: {
        url: string;
        blockInStr: string;
        trailingCommaInStr: string;
        items: number[];
      };
    }>(raw);

    expect(parsed.name).toBe("test");
    expect(parsed.nested.url).toBe("https://example.com/api?q=1//not-a-comment");
    expect(parsed.nested.blockInStr).toBe("/* also not comment */");
    expect(parsed.nested.trailingCommaInStr).toBe("a, } b, ]");
    expect(parsed.nested.items).toEqual([1, 2, 3]);
  });

  it("handles BOM gracefully", () => {
    const raw = `\uFEFF{ "bom": true }`;
    expect(parseJsonc<{ bom: boolean }>(raw)).toEqual({ bom: true });
  });

  it("handles escaped quotes properly in strings", () => {
    const raw = `{"quote": "escaped \\" quote // not comment", "next": 1,}`;
    expect(parseJsonc<{ quote: string; next: number }>(raw)).toEqual({
      quote: 'escaped " quote // not comment',
      next: 1,
    });
  });
});
